# Generated by Django 4.2.2 on 2026-01-04 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_routeexclusion_required_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=50, unique=True)),
                ('region_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TableProvince',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_name', models.CharField(max_length=100)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tableregion')),
            ],
        ),
        migrations.CreateModel(
            name='TableMunicipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipality_name', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tableprovince')),
            ],
        ),
        migrations.CreateModel(
            name='TableBarangay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay_name', models.CharField(max_length=100)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tablemunicipality')),
            ],
        ),
        migrations.AddIndex(
            model_name='tableprovince',
            index=models.Index(fields=['region'], name='app_tablepr_region__cd4be6_idx'),
        ),
        migrations.AddIndex(
            model_name='tablemunicipality',
            index=models.Index(fields=['province'], name='app_tablemu_provinc_739c47_idx'),
        ),
        migrations.AddIndex(
            model_name='tablebarangay',
            index=models.Index(fields=['municipality'], name='app_tableba_municip_432b7e_idx'),
        ),
    ]
